version: "3.9"

services:
  photography-portfolio-frontend:
    image: photography-portfolio-frontend:dev
    container_name: photography-portfolio-frontend
    networks:
      - photographyportfolio
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 3100:3100
    environment:
      - API_KEY=${API_KEY}
      - CHOKIDAR_USEPOLLING=true

networks:
  photographyportfolio:
    name: photographyportfolio