version: "3.9"

services:
  photography-portfolio-frontend:
    image: photography-portfolio-frontend
    container_name: photography-portfolio-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
