version: "3.8"

services:
  frontend:
    image: personal-website-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000

