version: "3.9"

services:
  personal-website-frontend:
    image: personal-website-frontend
    container_name: personal-website-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
